export const FEED_REACTION_ICON_SIZE = 18;
export const FEED_REACTION_PILL_MIN_WIDTH = 76;
export const FEED_REACTION_PILL_HORIZONTAL_PADDING = 10;
export const FEED_REACTION_PILL_VERTICAL_PADDING = 6;
export const FEED_REACTION_PILL_GAP = 6;
export const FEED_REACTION_VALUE_MIN_WIDTH = 28;
